FROM mcr.microsoft.com/devcontainers/base:alpine-3.20

COPY post-create-command.fish /usr/local/libexec/post-create-command
RUN apk add --no-cache fish && chmod 755 /usr/local/libexec/post-create-command

SHELL ["/usr/bin/fish"]
